# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 0.7
  - 1.0
  - nightly

notifications:
  email: false

matrix:
  allow_failures:
    - julia: 0.7
    - julia: nightly

after_success:
# build documentation
  - julia -e 'cd(Pkg.dir("IntervalOptimisation")); ps=Pkg.PackageSpec(name="Documenter", version="0.19"); Pkg.add(ps); Pkg.pin(ps); include(joinpath("docs", "make.jl"))'
# push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("IntervalOptimisation")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
